In [11]:
import numpy as np

def H(x, y):
    return -6*(x**2)+16/5*(y**2)+16*x*y-16/5*x-48/5*y

# Метод Брауна–Робинсон (итерационный алгоритм)
def braun_robinson(C, epsilon):
    n, m = C.shape # число стратегий игроков

    A = np.zeros(n) # массив из n нулей
    B = np.zeros(m) # массив из m нулей

    x_count = np.zeros(n)
    y_count = np.zeros(m)

    I_A = np.random.randint(0, 2) # стратегия игрока A (выбирается рандомно)
    I_B = np.random.randint(0, 2) # стратегия игрока B (выбирается рандомно)

    A = C[:,I_B] # рандомный столбец C
    B = C[I_A,:] # рандомная строка C

    x_count[0] += 1
    y_count[0] += 1
    
    I_A = 0
    I_B = 0

    v_up_arr = []
    v_down_arr= []

    eps = 1000
    k = 0

    while eps >= epsilon:
        k+=1 # номер итерации
        x_count[I_A] += 1 # увеличение числа выборов одной из стратегий игрока А
        y_count[I_B] += 1 # увеличение числа выборов одной из стратегий игрока B
        v_up   = max(A)/k # верхняя цена игры
        v_down = min(B)/k # нижняя цена игры
        v_up_arr.append(v_up) # массив верхних цен
        v_down_arr.append(v_down) # массив нижних цен

        eps = min(v_up_arr) - max(v_down_arr) # погрешность  
        
        A_max_indices = np.where(A == np.max(A))[0]  # Получаем индексы всех максимумов A
        I_A = np.random.choice(A_max_indices)  # Выбираем случайный индекс A
        
        B_min_indices = np.where(B == np.min(B))[0]  # Получаем индексы всех минимумов B
        I_B = np.random.choice(B_min_indices)  # Выбираем случайный индекс B
        
        A = A+C[:,I_B]
        B = B+C[I_A,:]

    return x_count/k, y_count/k # приближенные смешанные стратегии
    
# основная программа

for N in range(1,33):
    print("N=",N,"\n")
    matr = np.zeros((N+1,N+1))
    for i in range(N+1):
        for j in range(N+1):
            x = i/N
            y = j/N
            matr[i][j] = round(H(x, y),3)

    print(matr,"\n")
    # массив индексов максимальных элементов в столбцах
    I_col_max = np.argmax(matr,axis=0) 
    # массив индексов минимальныз элементов в строках
    I_raw_min = np.argmin(matr,axis=1)

    arr_max_elem = []
    arr_min_elem = []

    n, m = matr.shape # размеры матрицы
    # массив минимальных элементов по строкам
    for p in range(n):
        arr_min_elem.append(matr[p,I_raw_min[p]]) 
    # массив максимальных элементов по столбцам    
    for l in range(m):
        arr_max_elem.append(matr[I_col_max[l],l])

    v_down_N = max(arr_min_elem) # Нижняя  цена игры
    v_up_N = min(arr_max_elem)   # Верхняя цена игры

    if v_down_N == v_up_N:
        H_point = v_up_N
        x_point = round(np.argmax(arr_min_elem)/N,3)
        y_point = round(np.argmin(arr_max_elem)/N,3)
        print("Есть седловая точка:\n")
        print("x=",x_point,"y=",y_point," ","H=",H_point)
    
    else:

        x_opt, y_opt = braun_robinson(matr,epsilon=0.01)
        x_point = np.argmax(x_opt)
        y_point = np.argmax(y_opt)
        print("Седловой точки нет, решение методом Брауна-Робинсон:\n")
        print("x=",np.round(x_point/N,3),"y=",np.round(y_point/N,3)," ","H=",matr[x_point][y_point],"\n")   






N= 1 

[[ 0.  -6.4]
 [-9.2  0.4]] 

Седловой точки нет, решение методом Брауна-Робинсон:

x= 0.0 y= 1.0   H= -6.4 

N= 2 

[[ 0.  -4.  -6.4]
 [-3.1 -3.1 -1.5]
 [-9.2 -5.2  0.4]] 

Есть седловая точка:

x= 0.5 y= 0.5   H= -3.1
N= 3 

[[ 0.    -2.844 -4.978 -6.4  ]
 [-1.733 -2.8   -3.156 -2.8  ]
 [-4.8   -4.089 -2.667 -0.533]
 [-9.2   -6.711 -3.511  0.4  ]] 

Седловой точки нет, решение методом Брауна-Робинсон:

x= 0.333 y= 0.667   H= -3.156 

N= 4 

[[ 0.    -2.2   -4.    -5.4   -6.4  ]
 [-1.175 -2.375 -3.175 -3.575 -3.575]
 [-3.1   -3.3   -3.1   -2.5   -1.5  ]
 [-5.775 -4.975 -3.775 -2.175 -0.175]
 [-9.2   -7.4   -5.2   -2.6    0.4  ]] 

Седловой точки нет, решение методом Брауна-Робинсон:

x= 0.5 y= 0.5   H= -3.1 

N= 5 

[[ 0.    -1.792 -3.328 -4.608 -5.632 -6.4  ]
 [-0.88  -2.032 -2.928 -3.568 -3.952 -4.08 ]
 [-2.24  -2.752 -3.008 -3.008 -2.752 -2.24 ]
 [-4.08  -3.952 -3.568 -2.928 -2.032 -0.88 ]
 [-6.4   -5.632 -4.608 -3.328 -1.792  0.   ]
 [-9.2   -7.792 -6.128 -4.208 -2.032  0.4 